project:
  type: website
  preview: 
    port: 8080
    browser: false
website:
  favicon: ./images/brilhante.png
  description: "A blog for learning with you!"
  open-graph: true
  reader-mode: true
  page-navigation: true
  back-to-top-navigation: true
  site-url: https://carolbalbs.github.io/blog-dicici-a-te # you must change this appropriately for RSS feeds to work properly
  title: "Didici a te!"
  navbar:
    logo: "/images/brilhos.png"
    right:
      - about.qmd
      - icon: github
        href: https://github.com/carolbalbs
      - icon: discord
        href: https://discord.com/users/carolbalbs#1441

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css    
    toc: true
    keep-md: true


